local_sqlite_project:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: '../local_sqlite_project_db.sqlite'
      schema_directory: 'file_path'
      #optional fields
#      extensions:
#        - "/path/to/sqlean/crypto.so"
